### ISSUE TITLE
留言板页面Database Query Error

### ISSUE THREAD

**Issue by ykla** [ihewro/typecho-theme-handsome#33]
报错500 Database Query Error

**Comment by ykla** [comment]
新建独立页面非留言板显示正常。

**Comment by ihewro** [comment]
在config.inc.php里加入
```
define('__TYPECHO_DEBUG__', true);
```

可以查看具体的错误输出，建议把错误输出贴上来便于解决问题

**Comment by ykla** [comment]
mysql

**Comment by ykla** [comment]
请问错误输出会显示在什么地方？

**Comment by ykla** [comment]
SQLSTATE[42000]: Syntax error or access violation: 1055 Expression #3 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'hmxs.typecho_comments.url' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by

Typecho_Db_Query_Exception: SQLSTATE[42000]: Syntax error or access violation: 1055 Expression #3 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'hmxs.typecho_comments.url' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by in /usr/local/www/nginx-dist/var/Typecho/Db/Adapter/Pdo.php:105
Stack trace:
#0 /usr/local/www/nginx-dist/var/Typecho/Db.php(352): Typecho_Db_Adapter_Pdo->query(Object(Typecho_Db_Query), Object(PDO), 1, 'SELECT')
#1 /usr/local/www/nginx-dist/var/Typecho/Db.php(382): Typecho_Db->query(Object(Typecho_Db_Query), 1)
#2 /usr/local/www/nginx-dist/usr/themes/handsome/functions.php(776): Typecho_Db->fetchAll(Object(Typecho_Db_Query))
#3 /usr/local/www/nginx-dist/usr/themes/handsome/guestbook.php(59): getFriendWall()
#4 /usr/local/www/nginx-dist/var/Widget/Archive.php(2018): require_once('/usr/local/www/...')
#5 /usr/local/www/nginx-dist/var/Typecho/Router.php(138): Widget_Archive->render()
#6 /usr/local/www/nginx-dist/index.php(23): Typecho_Router::dispatch()
#7 {main}

**Comment by ihewro** [comment]
你使用的是typecho正式版本吗？

可能是typecho 在 PHP7环境有一些问题

**Comment by ykla** [comment]
不是正式版。是开发板。正式版不支持PHP7。

**Comment by xlsw** [comment]
不会吧，我就是在PHP7下运行1.0的正式版的呀？

**Comment by mingyue2017** [comment]
我也碰到这个问题了！
