### ISSUE TITLE
使用sqlite数据库报错

### ISSUE THREAD

**Issue by JoeyChow** [ihewro/typecho-theme-handsome#38]
SQLSTATE[HY000]: General error: 1 no such function: RAND

exception 'Typecho_Db_Query_Exception' with message 'SQLSTATE[HY000]: General error: 1 no such function: RAND' in /data/home/qxu1146520218/htdocs/var/Typecho/Db/Adapter/Pdo.php:93
Stack trace:
#0 /data/home/qxu1146520218/htdocs/var/Typecho/Db.php(319): Typecho_Db_Adapter_Pdo->query(Object(Typecho_Db_Query), Object(PDO), 1, 'SELECT')
#1 /data/home/qxu1146520218/htdocs/var/Typecho/Db.php(349): Typecho_Db->query(Object(Typecho_Db_Query), 1)
#2 /data/home/qxu1146520218/htdocs/usr/themes/handsome/functions.php(717): Typecho_Db->fetchAll(Object(Typecho_Db_Query))
#3 /data/home/qxu1146520218/htdocs/usr/themes/handsome/sidebar.php(66): theme_random_posts(Object(Widget_Archive))
#4 /data/home/qxu1146520218/htdocs/var/Widget/Archive.php(1918): require('/data/home/qxu1...')
#5 /data/home/qxu1146520218/htdocs/usr/themes/handsome/index.php(90): Widget_Archive->need('sidebar.php')
#6 /data/home/qxu1146520218/htdocs/var/Widget/Archive.php(2001): require_once('/data/home/qxu1...')
#7 /data/home/qxu1146520218/htdocs/var/Typecho/Router.php(138): Widget_Archive->render()
#8 /data/home/qxu1146520218/htdocs/index.php(23): Typecho_Router::dispatch()
#9 {main}

**Comment by ihewro** [comment]
主题内使用的调用数据库的某些函数不支持sqlite，暂时只能支持mysql。
